#!/usr/bin/env bash
#
# WorkOps Cloud Agent — start phase.
#
# Per-boot reconciliation: bring up Docker + the local Supabase stack, make the
# database look like a hosted Supabase project (role grants + storage bucket),
# write .env.local for the Next.js app, and seed demo data. Idempotent and
# returns once the backend is ready. The Next.js dev server runs separately as
# the `next-dev` terminal.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/lib.sh"
cd "$REPO_ROOT"

# --- 1. Docker + Supabase stack ----------------------------------------------
ensure_docker
log "Starting local Supabase stack..."
npx --yes supabase start

STATUS_JSON="$(npx --yes supabase status -o json)"
read_key() { printf '%s' "$STATUS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin).get('$1',''))"; }
API_URL="$(read_key API_URL)"
ANON_KEY="$(read_key ANON_KEY)"
SERVICE_ROLE_KEY="$(read_key SERVICE_ROLE_KEY)"

DB_CONTAINER="$(supabase_db_container)"
if [ -z "$DB_CONTAINER" ]; then
  log "Supabase DB container not found" >&2
  exit 1
fi

# --- 2. Match hosted Supabase role grants (idempotent) -----------------------
log "Applying standard Supabase role grants..."
docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=1 \
  < "$SCRIPT_DIR/local-supabase-grants.sql" >/dev/null

# --- 3. Write .env.local for the Next.js app ---------------------------------
log "Writing .env.local..."
SECRET="$(openssl rand -hex 32)"
cat > "$REPO_ROOT/.env.local" <<EOF
# Auto-generated by .cursor/start.sh for the local Supabase stack.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
NEXT_PUBLIC_APP_URL=http://localhost:3000

SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
NOTIFICATIONS_PROCESS_SECRET=$SECRET
CRON_SECRET=$SECRET

# Optional integrations (left blank for local dev)
RESEND_API_KEY=
RESEND_FROM_EMAIL=WorkOps <onboarding@resend.dev>
NEXT_PUBLIC_MAPBOX_TOKEN=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
EOF

# --- 4. Storage bucket + demo data (idempotent) ------------------------------
log "Ensuring storage buckets (npm run db:audit)..."
npm run db:audit >/tmp/db-audit.log 2>&1 || log "db:audit reported warnings (see /tmp/db-audit.log)."

log "Seeding Cape Shuttle Ops demo data..."
node scripts/setup-cape-shuttle-demo.mjs || log "Demo seed reported an issue (non-fatal)."

log "start complete — backend ready. Next.js dev server runs in the 'next-dev' terminal."
